#!/usr/bin/env python3
"""
CSV File Analyzer and Statistics Generator
Generated by ScripGen
Aligned with the Alsania AI Protocol v1.0
"""

import csv
import sys
import os
from collections import Counter, defaultdict
from statistics import mean, median, stdev
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class CSVAnalyzer:
    def __init__(self, file_path):
        self.file_path = file_path
        self.data = []
        self.headers = []

    def load_data(self):
        """Load CSV data from file"""
        try:
            with open(self.file_path, 'r', newline='', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                self.headers = reader.fieldnames
                self.data = list(reader)
            logger.info(f"Loaded {len(self.data)} rows with {len(self.headers)} columns")
        except FileNotFoundError:
            logger.error(f"File not found: {self.file_path}")
            sys.exit(1)
        except Exception as e:
            logger.error(f"Error loading CSV: {e}")
            sys.exit(1)

    def analyze_numeric_columns(self):
        """Analyze numeric columns for statistics"""
        numeric_stats = {}

        for header in self.headers:
            try:
                values = [float(row[header]) for row in self.data if row[header].strip()]
                if values:
                    numeric_stats[header] = {
                        'count': len(values),
                        'mean': mean(values),
                        'median': median(values),
                        'min': min(values),
                        'max': max(values),
                        'std_dev': stdev(values) if len(values) > 1 else 0
                    }
            except (ValueError, TypeError):
                continue

        return numeric_stats

    def analyze_text_columns(self):
        """Analyze text columns for frequency"""
        text_stats = {}

        for header in self.headers:
            values = [row[header] for row in self.data if row[header].strip()]
            if values:
                counter = Counter(values)
                text_stats[header] = {
                    'unique_values': len(counter),
                    'most_common': counter.most_common(5),
                    'total_values': len(values)
                }

        return text_stats

    def generate_report(self):
        """Generate comprehensive analysis report"""
        print(f"\n{'='*60}")
        print(f"CSV ANALYSIS REPORT")
        print(f"File: {os.path.basename(self.file_path)}")
        print(f"{'='*60}")

        print(f"\n📊 BASIC INFO:")
        print(f"  Rows: {len(self.data)}")
        print(f"  Columns: {len(self.headers)}")
        print(f"  Headers: {', '.join(self.headers)}")

        # Numeric analysis
        numeric_stats = self.analyze_numeric_columns()
        if numeric_stats:
            print(f"\n🔢 NUMERIC COLUMNS:")
            for col, stats in numeric_stats.items():
                print(f"\n  {col}:")
                print(f"    Count: {stats['count']}")
                print(f"    Mean: {stats['mean']:.2f}")
                print(f"    Median: {stats['median']:.2f}")
                print(f"    Range: {stats['min']:.2f} - {stats['max']:.2f}")
                if stats['std_dev'] > 0:
                    print(f"    Std Dev: {stats['std_dev']:.2f}")

        # Text analysis
        text_stats = self.analyze_text_columns()
        if text_stats:
            print(f"\n📝 TEXT COLUMNS:")
            for col, stats in text_stats.items():
                print(f"\n  {col}:")
                print(f"    Unique values: {stats['unique_values']}")
                print(f"    Total values: {stats['total_values']}")
                print(f"    Most common:")
                for value, count in stats['most_common'][:3]:
                    print(f"      '{value}': {count} times")

        print(f"\n{'='*60}")

def main():
    if len(sys.argv) != 2:
        print("Usage: python csv_analyzer.py <csv_file>")
        sys.exit(1)

    file_path = sys.argv[1]

    if not os.path.exists(file_path):
        print(f"Error: File '{file_path}' not found")
        sys.exit(1)

    analyzer = CSVAnalyzer(file_path)
    analyzer.load_data()
    analyzer.generate_report()

    logger.info("Analysis completed successfully!")

if __name__ == "__main__":
    main()