import { IntegrationFile
} from '../../core/types';

/**
 * VS Code Integration
 * Generates code snippets for Visual Studio Code
 * Alsania Protocol v1.0 - Built by Sigma, Powered by Echo
 */

export interface VSSnippetConfig {
  name: string;
  prefix: string;
  body: string[];
  description: string;
  scope?: string;
  language?: string;
}

export class VSCodeIntegration {
  private logger: any;

  constructor(logger: any) {
    this.logger = logger;
  }
  /**
   * Generate VS Code snippet files from script code
   */
  async generateSnippetFiles(
    scriptCode: string,
    scriptLanguage: 'python' | 'bash',
    config?: Partial<VSSnippetConfig>
  ): Promise<IntegrationFile[]> {
    const defaultConfig: VSSnippetConfig = {
      name: 'Generated Script',
      prefix: 'genscript',
      body: [],
      description: 'Generated by ScripGen - Alsania Protocol v1.0',
      scope: scriptLanguage === 'python' ? 'python' : 'shellscript',
    };

    const snippetConfig = { ...defaultConfig, ...config
    };

    // Analyze script to generate appropriate snippet
    const analyzedConfig = await this.analyzeScript(scriptCode, scriptLanguage, snippetConfig);

    // Generate snippet file content
    const snippetContent = this.generateSnippetContent(analyzedConfig);

    const filename = `${analyzedConfig.name.toLowerCase().replace(/[^a-z0-9
      ]+/g, '_')
    }_snippets.code-snippets`;

    return [
      {
        type: 'vscode',
        filename,
        content: snippetContent,
        path: '.vscode/',
        executable: false,
      },
    ];
  }
  /**
   * Analyze script code to generate optimal VS Code snippet
   */
  private async analyzeScript(
    scriptCode: string,
    language: 'python' | 'bash',
    config: VSSnippetConfig
  ): Promise<VSSnippetConfig> {
    const lines = scriptCode.split('\n').filter(line => line.trim());

    // Extract meaningful parts for snippet
    const body: string[] = [];
    let inMainLogic = false;

    for (const line of lines) {
      // Skip shebang and comments at the top
      if (line.startsWith('#!') || (line.startsWith('#') && !inMainLogic)) {
        continue;
      }
      // For Python, look for main logic after imports
      if (language === 'python') {
        if (line.includes('import ') || line.includes('from ')) {
          continue;
        }
        if (line.includes('def main():') || line.includes('if __name__')) {
          inMainLogic = true;
          body.push(line);
        } else if (inMainLogic && line.trim()) {
          // Convert to snippet format with placeholders
          let processedLine = line
            .replace(/['"]([^'"
          ]*)['"]/g, '"${
              1:$1
            }"')  // Add placeholders for strings
            .replace(/\b(\w+)\s*=\s*/g, (match, varName) => {
              // Add placeholders for variable assignments
              if (varName.length > 2) { // Avoid common keywords
                return `${varName
                } = \${${body.length + 1
                  }:${varName
                  }
                }`;
              }
              return match;
            });

          body.push(processedLine);
          }
        } else if (language === 'bash') {
          // For Bash, include main logic
        if (!line.startsWith('#') && line.trim()) {
          let processedLine = line
            .replace(/['"]([^'"
            ]*)['"]/g, '"${
                1:$1
              }"')  // Add placeholders for strings
            .replace(/(\w+)\s*=\s*/g, (match, varName) => {
                // Add placeholders for variables
              return `${varName
                }="\${${body.length + 1}:${varName}}"`;
              });

          body.push(processedLine);
            }
          }
        }
        // Set appropriate prefix and description based on content
    if (language === 'python') {
      if (scriptCode.includes('csv') || scriptCode.includes('pandas')) {
        config.name = 'Python Data Analysis';
        config.prefix = 'pydata';
        config.description = 'Python script for data analysis and processing';
          } else if (scriptCode.includes('logging') || scriptCode.includes('logger')) {
        config.name = 'Python Logging Script';
        config.prefix = 'pylog';
        config.description = 'Python script with comprehensive logging';
          } else {
        config.name = 'Python Script Boilerplate';
        config.prefix = 'pyboil';
        config.description = 'Python script boilerplate with error handling';
          }
        } else {
      if (scriptCode.includes('backup') || scriptCode.includes('cp ') || scriptCode.includes('rsync')) {
        config.name = 'Bash Backup Script';
        config.prefix = 'bashbackup';
        config.description = 'Bash script for file backup operations';
          } else if (scriptCode.includes('monitor') || scriptCode.includes('top') || scriptCode.includes('free')) {
        config.name = 'Bash System Monitor';
        config.prefix = 'bashmonitor';
        config.description = 'Bash script for system monitoring';
          } else {
        config.name = 'Bash Script Template';
        config.prefix = 'bashtemp';
        config.description = 'Bash script template with error handling';
          }
        }

    config.body = body.slice(0,
        20); // Limit to reasonable snippet size

    return config;
      }
      /**
   * Generate the VS Code snippet JSON content
   */
  private generateSnippetContent(config: VSSnippetConfig): string {
    const snippet = {
          [config.name
          ]: {
        prefix: config.prefix,
        body: config.body,
        description: config.description,
        scope: config.scope,
          }
        };

    return JSON.stringify(snippet,
        null,
        2);
      }
      /**
   * Validate VS Code integration environment
   */
  async validateEnvironment(): Promise<{ valid: boolean; issues: string[]
      }> {
    const issues: string[] = [];

    // Check if VS Code is installed
    try {
      const { execSync
          } = require('child_process');
      execSync('which code',
          { stdio: 'pipe'
          });
        } catch {
      issues.push('VS Code CLI (code) is not installed or not in PATH');
        }
        // Check if .vscode directory exists in current project
    try {
      require('fs').accessSync('.vscode');
        } catch {
      issues.push('No .vscode directory found in current workspace');
        }

    return {
      valid: issues.length === 0,
      issues
        };
      }
      /**
   * Install generated snippet files
   */
  async installSnippets(snippetFiles: IntegrationFile[]): Promise<void> {
    const fs = require('fs').promises;
    const path = require('path');

    const vscodeDir = '.vscode';

    // Ensure .vscode directory exists
    await fs.mkdir(vscodeDir,
        { recursive: true
        });

    // Install each snippet file
    for (const file of snippetFiles) {
      const targetPath = path.join(vscodeDir, file.filename);
      await fs.writeFile(targetPath, file.content, 'utf8');
      this.logger.info(`Installed VS Code snippet: ${targetPath
          }`);
        }
        // Reload VS Code window if possible
    try {
      const { execSync
          } = require('child_process');
      execSync('code --reload-window',
          { stdio: 'pipe'
          });
      this.logger.info('Reloaded VS Code window');
        } catch (error) {
      this.logger.warn('Could not reload VS Code automatically');
        }
      }
      /**
   * Generate multiple snippets from a script collection
   */
  async generateSnippetCollection(
    scripts: Array<{ code: string; language: 'python' | 'bash'; name: string
      }>
  ): Promise<IntegrationFile[]> {
    const allSnippets: Record<string, any> = {};

    for (const script of scripts) {
      const config = await this.analyzeScript(script.code, script.language,
          {
        name: script.name,
        prefix: script.name.toLowerCase().replace(/[^a-z0-9
            ]+/g, ''),
        body: [],
        description: `Generated snippet for ${script.name
            }`,
          });

      allSnippets[config.name
          ] = {
        prefix: config.prefix,
        body: config.body,
        description: config.description,
        scope: config.scope,
          };
        }

    const collectionContent = JSON.stringify(allSnippets,
        null,
        2);
    const filename = 'scrypgen_snippets.code-snippets';

    return [
          {
        type: 'vscode',
        filename,
        content: collectionContent,
        path: '.vscode/',
        executable: false,
          },
        ];
      }
    }