#!/usr/bin/env bash
#
# Automated backup script for important files
# Generated by ScripGen
# Aligned with the Alsania AI Protocol v1.0
#

set -e

# Configuration
SOURCE_DIR="${HOME}/Documents"
BACKUP_DIR="${HOME}/backups"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_NAME="backup_${TIMESTAMP}"

# Create backup directory if it doesn't exist
mkdir -p "${BACKUP_DIR}"

# Main backup logic
echo "Starting backup of ${SOURCE_DIR} to ${BACKUP_DIR}/${BACKUP_NAME}"

# Create timestamped backup directory
BACKUP_PATH="${BACKUP_DIR}/${BACKUP_NAME}"
mkdir -p "${BACKUP_PATH}"

# Copy files with progress indication
cp -rv "${SOURCE_DIR}"/* "${BACKUP_PATH}/" 2>/dev/null || true

# Create archive
echo "Creating compressed archive..."
cd "${BACKUP_DIR}"
tar -czf "${BACKUP_NAME}.tar.gz" "${BACKUP_NAME}"

# Cleanup uncompressed backup
rm -rf "${BACKUP_NAME}"

echo "Backup completed successfully!"
echo "Archive location: ${BACKUP_DIR}/${BACKUP_NAME}.tar.gz"
echo "Total size: $(du -sh "${BACKUP_DIR}/${BACKUP_NAME}.tar.gz" | cut -f1)"