import {
  Integration,
  IntegrationFile,
  GeneratorConfig,
  Logger,
  NLPAnalysis,
} from "./types";

export class IntegrationManager {
  private logger: Logger;

  constructor(config: GeneratorConfig, logger: Logger) {
    this.logger = logger;
    // Config stored for future extensibility
    void config;
  }

  async generateIntegrationFiles(
    code: string,
    _language: "python" | "bash",
    integrations: Integration[],
    _nlpAnalysis: NLPAnalysis,
  ): Promise<IntegrationFile[]> {
    const files: IntegrationFile[] = [];

    for (const integration of integrations) {
      if (!integration.enabled) continue;

      try {
        this.logger.debug(`Generating ${integration.type
        } integration files`);

        switch (integration.type) {
          case "nemo":
            files.push(...(await this.generateNemoFiles(code)));
            break;
          case "kde-connect":
            files.push(...(await this.generateKDEFiles(code)));
            break;
          case "vscode":
            files.push(...(await this.generateVSCodeFiles(code)));
            break;
        }
      } catch (error) {
        this.logger.warn(
          `Failed to generate ${integration.type
        } integration`,
          error,
        );
      }
    }

    return files;
  }

  private async generateNemoFiles(_code: string): Promise<IntegrationFile[]> {
    // Generate .nemo_action file
    const actionName = "Generated Action";
    const actionContent = `[Nemo Action
    ]
Name=${actionName
    }
Comment=Generated by Universal Script Generator
Exec=/path/to/script.sh %F
Icon-Name=application-x-executable
Selection=any
Extensions=any;
Mimetypes=application/x-shellscript;`;

    return [
      {
        type: "nemo",
        filename: `${actionName.toLowerCase().replace(/\s+/g,
          "_")
        }.nemo_action`,
        content: actionContent,
        path: "~/.local/share/nemo/actions/",
        executable: false,
      },
    ];
  }

  private async generateKDEFiles(code: string): Promise<IntegrationFile[]> {
    // Generate KDE Connect command configuration
    const commandConfig = `{
      "name": "Generated Command",
      "command": "${code.split("\n")[0] || "echo Generated"}",
      "description": "Generated by Universal Script Generator"
    }`;

    return [
      {
        type: "kde-connect",
        filename: "generated_command.json",
        content: commandConfig,
        path: "~/.config/kdeconnect/",
        executable: false,
      },
    ];
  }

  private async generateVSCodeFiles(code: string): Promise<IntegrationFile[]> {
    // Generate VS Code snippet
    const snippet = `{
      "Generated Script": {
        "prefix": "genscript",
        "body": [${code
      .split("\n")
      .map((line) => `"${line.replace(/"/g, '\\"')}"`)
      .join(",\n      ")
          }
        ],
        "description": "Generated by Universal Script Generator"
      }
    }`;

    return [
      {
        type: "vscode",
        filename: "generated-scripts.code-snippets",
        content: snippet,
        path: ".vscode/",
        executable: false,
      },
    ];
  }
}