import { IntegrationFile
} from '../../core/types';

/**
 * Nemo File Manager Integration
 * Generates .nemo_action files for context menu integration
 * Alsania Protocol v1.0 - Built by Sigma, Powered by Echo
 */

export interface NemoActionConfig {
  name: string;
  comment: string;
  exec: string;
  icon: string;
  selection: 'any' | 'notnone' | 'single' | 'multiple';
  extensions: string[];
  mimetypes: string[];
  dependencies: string[];
}

export class NemoIntegration {
  private logger: any;

  constructor(logger: any) {
    this.logger = logger;
  }
  /**
   * Generate Nemo action files from script code
   */
  async generateActionFiles(
    scriptCode: string,
    scriptPath: string,
    config?: Partial<NemoActionConfig>
  ): Promise<IntegrationFile[]> {
    const defaultConfig: NemoActionConfig = {
      name: 'Generated Script Action',
      comment: 'Generated by ScripGen - Alsania Protocol v1.0',
      exec: scriptPath,
      icon: 'application-x-executable',
      selection: 'any',
      extensions: ['*'
      ],
      mimetypes: ['application/octet-stream'
      ],
      dependencies: []
    };

    const actionConfig = { ...defaultConfig, ...config
    };

    // Analyze script to determine appropriate action properties
    const analyzedConfig = await this.analyzeScript(scriptCode, actionConfig);

    // Generate .nemo_action file content
    const actionContent = this.generateActionContent(analyzedConfig);

    const filename = `${analyzedConfig.name.toLowerCase().replace(/[^a-z0-9
      ]+/g, '_')
    }.nemo_action`;

    return [
      {
        type: 'nemo',
        filename,
        content: actionContent,
        path: '~/.local/share/nemo/actions/',
        executable: false,
      },
    ];
  }
  /**
   * Analyze script code to determine optimal action configuration
   */
  private async analyzeScript(
    scriptCode: string,
    config: NemoActionConfig
  ): Promise<NemoActionConfig> {
    // Analyze script content to customize the action
    const analysis = {
      hasFileInput: scriptCode.includes('$1') || scriptCode.includes('%F'),
      hasDirectoryInput: scriptCode.includes('directory') || scriptCode.includes('folder'),
      isCompression: scriptCode.includes('zip') || scriptCode.includes('tar') || scriptCode.includes('compress'),
      isBackup: scriptCode.includes('backup') || scriptCode.includes('copy'),
      isAnalysis: scriptCode.includes('analyze') || scriptCode.includes('stats'),
      isConversion: scriptCode.includes('convert') || scriptCode.includes('transform'),
    };

    // Customize based on analysis
    if (analysis.isCompression) {
      config.name = 'Compress Files';
      config.comment = 'Compress selected files into an archive';
      config.icon = 'archive-insert';
      config.selection = 'notnone';
      config.extensions = ['*'
      ];
      config.mimetypes = ['application/octet-stream'
      ];
    } else if (analysis.isBackup) {
      config.name = 'Backup Files';
      config.comment = 'Create backup of selected files';
      config.icon = 'document-save';
      config.selection = 'notnone';
    } else if (analysis.isAnalysis) {
      config.name = 'Analyze Files';
      config.comment = 'Analyze selected files and generate statistics';
      config.icon = 'document-properties';
      config.selection = 'notnone';
      config.extensions = ['txt', 'csv', 'json', 'log'
      ];
    } else if (analysis.isConversion) {
      config.name = 'Convert Files';
      config.comment = 'Convert selected files to different format';
      config.icon = 'document-convert';
      config.selection = 'single';
    }
    // Adjust execution command based on script type
    if (scriptCode.includes('#!/usr/bin/env python3')) {
      config.exec = `python3 "${config.exec}" %F`;
    } else if (scriptCode.includes('#!/usr/bin/env bash')) {
      config.exec = `bash "${config.exec}" %F`;
    } else {
      config.exec = `${config.exec
      } %F`;
    }

    return config;
  }
  /**
   * Generate the .nemo_action file content
   */
  private generateActionContent(config: NemoActionConfig): string {
    const extensions = config.extensions.length > 0 ? config.extensions.join(';') : 'any';
    const mimetypes = config.mimetypes.length > 0 ? config.mimetypes.join(';') : 'application/octet-stream';

    return `[Nemo Action
    ]
Name=${config.name
    }
Comment=${config.comment
    }
Exec=${config.exec
    }
Icon-Name=${config.icon
    }
Selection=${config.selection
    }
Extensions=${extensions
    };
Mimetypes=${mimetypes
    };
Dependencies=${config.dependencies.join(',') || 'none'
    }
Quote=double
EscapeSpaces=true
`;
  }
  /**
   * Validate Nemo integration environment
   */
  async validateEnvironment(): Promise<{ valid: boolean; issues: string[]
  }> {
    const issues: string[] = [];

    // Check if Nemo is installed
    try {
      const { execSync
      } = require('child_process');
      execSync('which nemo',
      { stdio: 'pipe'
      });
    } catch {
      issues.push('Nemo file manager is not installed');
    }
    // Check actions directory
    const actionsDir = require('os').homedir() + '/.local/share/nemo/actions';
    try {
      require('fs').accessSync(actionsDir);
    } catch {
      issues.push(`Nemo actions directory does not exist: ${actionsDir
      }`);
    }

    return {
      valid: issues.length === 0,
      issues
    };
  }
  /**
   * Install generated action files
   */
  async installActions(actionFiles: IntegrationFile[]): Promise<void> {
    const fs = require('fs').promises;
    const path = require('path');
    const os = require('os');

    const actionsDir = path.join(os.homedir(), '.local', 'share', 'nemo', 'actions');

    // Ensure directory exists
    await fs.mkdir(actionsDir,
    { recursive: true
    });

    // Install each action file
    for (const file of actionFiles) {
      const targetPath = path.join(actionsDir, file.filename);
      await fs.writeFile(targetPath, file.content, 'utf8');
      this.logger.info(`Installed Nemo action: ${targetPath
      }`);
    }
    // Restart Nemo if running
    try {
      const { execSync
      } = require('child_process');
      execSync('nemo --quit',
      { stdio: 'pipe'
      });
      this.logger.info('Restarted Nemo file manager');
    } catch (error) {
      this.logger.warn('Could not restart Nemo automatically');
    }
  }
}